# Generated by Django 5.0.1 on 2024-07-10 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipon_goodbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timezone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.CharField(max_length=255)),
                ('timezone', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='gasto',
            name='timezone',
            field=models.CharField(default='Europe/London', max_length=255),
            preserve_default=False,
        ),
    ]
