# Generated by Django 5.0.1 on 2024-07-19 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipon_goodbot', '0003_alter_gasto_telegram_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.IntegerField()),
                ('amount_spent', models.FloatField(default=0)),
                ('date_spent', models.DateTimeField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('date_timezone', models.CharField(max_length=255)),
                ('expense_comment', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameModel(
            old_name='Timezone',
            new_name='UserTimezone',
        ),
        migrations.DeleteModel(
            name='Gasto',
        ),
    ]
