# Generated by Django 4.2.2 on 2023-09-09 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todolist', '0002_rename_todo_item_todo_todo_alter_todo_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todo_rank', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
