# Generated by Django 4.2.2 on 2023-09-28 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_todorank'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
