# Generated by Django 4.2.2 on 2023-10-12 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0004_todo_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
