# Generated by Django 4.2.2 on 2023-09-25 06:49

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogentry',
            name='blog_body',
            field=ckeditor.fields.RichTextField(max_length=3200),
        ),
    ]
