# Generated by Django 4.2.2 on 2023-07-02 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_calendar', '0002_calendar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendar',
            old_name='body',
            new_name='detail',
        ),
        migrations.RenameField(
            model_name='calendar',
            old_name='subject',
            new_name='todo',
        ),
    ]
