# Generated by Django 4.2.2 on 2023-09-06 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_calendar', '0002_calendar_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_entries', to=settings.AUTH_USER_MODEL),
        ),
    ]
