# Generated by Django 4.2.2 on 2023-07-02 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_calendar', '0003_rename_body_calendar_detail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='detail',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
