# Generated by Django 4.2.2 on 2023-12-01 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('customized', models.BooleanField(default=False)),
                ('type', models.TextField(max_length=24)),
                ('image', models.ImageField(upload_to='D:\\python\\CS50W\\projects\\montano\\montano\\skc/media')),
                ('price', models.IntegerField(default=0)),
                ('cost', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='products',
        ),
    ]
