# Generated by Django 4.2.2 on 2023-12-01 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skc', '0002_product_delete_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(max_length=24),
        ),
    ]
