# Generated by Django 4.2.2 on 2023-12-01 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skc', '0003_alter_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='squared',
            field=models.BooleanField(default=False),
        ),
    ]
