# Generated by Django 4.2.2 on 2023-12-13 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skc', '0009_alter_product_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='squared',
        ),
        migrations.AddField(
            model_name='product',
            name='display',
            field=models.BooleanField(default=False),
        ),
    ]
