# Generated by Django 4.2.2 on 2023-12-13 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skc', '0010_remove_product_squared_product_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('regular', 'Regular'), ('customized', 'Customized'), ('mini', 'Mini'), ('bento', 'Bento'), ('bread-pastries', 'Bread & Pastries'), ('drinks', 'Drinks'), ('addons', 'Add-ons')], max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='display',
            field=models.BooleanField(default=True),
        ),
    ]
