# Generated by Django 4.2.2 on 2023-12-13 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skc', '0011_product_category_alter_product_display'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('regular', 'Regular'), ('mini', 'Mini'), ('bento', 'Bento'), ('bread-pastries', 'Bread & Pastries'), ('drinks', 'Drinks'), ('addons', 'Add-ons')], max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('birthday', 'birthday'), ('christening', 'christening'), ('valentine', 'valentine'), ('wedding', 'wedding')], max_length=24, null=True),
        ),
    ]
