# Generated by Django 4.2.2 on 2023-12-21 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skc', '0013_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
