# Generated by Django 4.2.2 on 2023-12-21 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skc', '0014_sale_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='created_on',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='price',
            new_name='total',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='product',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='quantity',
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='skc.product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skc.sale')),
            ],
        ),
    ]
