# Generated by Django 4.2.2 on 2024-01-14 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skc', '0015_rename_created_on_sale_date_rename_price_sale_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discontinued',
            field=models.BooleanField(default=False),
        ),
    ]
